// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAchLRtlojxQUNADR9nRbCM_1XGF7AYot0',
    appId: '1:862484008523:web:0cffcbd3842e1e14d847ce',
    messagingSenderId: '862484008523',
    projectId: 'halfswift-driving-db',
    authDomain: 'halfswift-driving-db.firebaseapp.com',
    storageBucket: 'halfswift-driving-db.firebasestorage.app',
    measurementId: 'G-9NC1GD5BZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2bnAbpO_Q1l1hezx7oitPUe8fCFCw3oE',
    appId: '1:862484008523:android:89418c687f02a207d847ce',
    messagingSenderId: '862484008523',
    projectId: 'halfswift-driving-db',
    storageBucket: 'halfswift-driving-db.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAchLRtlojxQUNADR9nRbCM_1XGF7AYot0',
    appId: '1:862484008523:web:2e2ca99d49700c8dd847ce',
    messagingSenderId: '862484008523',
    projectId: 'halfswift-driving-db',
    authDomain: 'halfswift-driving-db.firebaseapp.com',
    storageBucket: 'halfswift-driving-db.firebasestorage.app',
    measurementId: 'G-8MY3BG96H5',
  );

}